image: docker:stable

services:
  - docker:dind

stages:
  - test
  - push
  - deploy

before_script:
  - docker info
  - apk update

test:
  image: python:3.6.8-alpine3.9
  stage: test
  before_script:
    - apk add --no-cache --virtual .build-deps gcc python3-dev musl-dev postgresql-dev jpeg-dev zlib-dev
    - pip install toolz
    - pip install -r requirements.txt
  script:
    - pycodestyle --exclude='manage.py, patient-management/settings.py, patient-management/gitlab-ci-settings.py, */tests.py, */migrations' .
    - python3 manage.py makemigrations --settings=patient-management.gitlab-ci-settings
    - python3 manage.py migrate --settings=patient-management.gitlab-ci-settings
    - pytest --ds=patient-management.gitlab-ci-settings --cov=core --cov=users --cov=consultations --disable-warnings

push to github:
  stage: push
  before_script:
    - apk add --quiet --no-cache git
    - 'which ssh-agent || ( apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "$GITLAB_USER_ID"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin git@github.com:pi2-fga/201901-TriagemHospitalar-PatientManagement.git
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git push origin $CI_COMMIT_REF_NAME --force

deploy production:
  stage: deploy
  variables:
    IMAGE_TAG: master
  before_script:
    - apk add --quiet --no-cache py-pip
    - pip install --quiet docker-compose==1.23.2
    - docker login registry.gitlab.com --username gitlab-ci-token --password $CI_BUILD_TOKEN
  script:
    - docker-compose -f docker-compose.production.yml pull
    - docker-compose -f docker-compose.production.yml build
    - docker-compose -f docker-compose.production.yml push
  environment:
    name: production
  only:
    - /^master$/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
  tags:
    - docker
